### ISSUE TITLE
No update when deleting screenshot in dashboard

### ISSUE THREAD

**Issue by Masy98** [NAAVOO/KonnichiwaClient#2]
When deleting a screenshot in the dashboard it takes you back to your "main" page but still shows the just deleted screenshot. You have to reload the page to update it.

**Comment by NAAVOO** [comment]
I will rewrite the dashboard soon. The delete button will be in the "main screen".

I'm not closing this issue until I fixed it :)

**Comment by NAAVOO** [comment]
Fixed with the newest dashboard design :smile:
